name: auth_service
description: The interface and models for an API providing access to auth.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  very_good_analysis: ^6.0.0

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^5.4.1
  mb_storage:
    path: ../mb_storage
