name: mb_storage
description: Mal bazar local storage dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4

dependencies:
  shared_preferences: ^2.2.0
