name: user_repository
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_core: ^3.8.1
  firebase_core_platform_interface: ^5.3.1
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  token_storage:
    path: ../token_storage
  supabase_client:
    path: ../../supabase_client
  persistent_storage:
    path: ../../storage/persistent_storage
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
